### ISSUE TITLE
consider using cf-xarray

### ISSUE THREAD

**Issue by dcherian** [data-exp-lab/yt_xarray#48]
Cool talk!

You should be able to use cf-xarray to do the translation from "CF names" to yt names: https://cf-xarray.readthedocs.io/en/latest/coord_axes.html

The advantage is that cf-xarray has a decent set of rules for auto-guessing names, e.g. `units="degrees_north"` => "latitude" variable.

You can also add your custom rules and still use the cf-xarray interface: https://cf-xarray.readthedocs.io/en/latest/custom-criteria.html

Another useful page: https://cf-xarray.readthedocs.io/en/latest/howtouse.html

**Comment by dcherian** [comment]
Very cool! Does it work well enough?

**Comment by dcherian** [comment]
Can you point me to the existing aliasing please?

**Comment by chrishavlin** [comment]
sure:

https://github.com/data-exp-lab/yt_xarray/blob/e0c80a41bd078278073caa9ded4f9518d5d37dae/yt_xarray/accessor/_xr_to_yt.py#L401 

some extra context:

* yt is strict about coordinate names: ('x', 'y', 'z') for cartesian coordinates, (radial_axis, 'latitude', 'longitude') where radial axis is either 'depth' or 'altitude' for geographic coordinates. So the aliasing linked above is where it decides how to map the coordinates of a field to those expected by yt. I don't expect this to be something that can be fully automated: yt_xarray is not meant only for cf-compliant data and not all cf-compliant data will map to yt coordinates. 
* the existing aliasing is just a dictionary that the user can change the key/value pairs and takes precedent over cf_xarray's automatic disambiguation and I added cf_xarray as an optional dep, so it will only even try if cf_xarray is installed.
